### ISSUE TITLE
Key names are being lowercases if they aren't long enough

### ISSUE THREAD

**Issue by dbousamra** [pureconfig/pureconfig#140]
I have some HOCON:

```
{
  settings {
    stormpath: {
      apiKey: "example"
    }
}
```

When I try to parse this as:

`case class Stormpath(apiKey: Option[String]) 
`
I get:

```
Caused by: pureconfig.error.KeyNotFoundException: Could not find the key settings.stormpath.apikey
	at pureconfig.ConfigConvert$$anonfun$improveFailure$1.applyOrElse(ConfigConvert.scala:119)
	at pureconfig.ConfigConvert$$anonfun$improveFailure$1.applyOrElse(ConfigConvert.scala:117)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure.recoverWith(Try.scala:203)
	at pureconfig.ConfigConvert$.improveFailure(ConfigConvert.scala:117)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:133)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$WrappedDefaultValueConfigConvert$class.fromWithDefault(ConfigConvert.scala:103)
	at pureconfig.ConfigConvert$$anon$2.fromWithDefault(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$$anon$2$$anonfun$fromConfigObject$3.apply(ConfigConvert.scala:143)
	at pureconfig.ConfigConvert$$anon$2$$anonfun$fromConfigObject$3.apply(ConfigConvert.scala:133)
	at scala.util.Success.flatMap(Try.scala:231)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:133)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$WrappedDefaultValueConfigConvert$class.fromWithDefault(ConfigConvert.scala:103)
	at pureconfig.ConfigConvert$$anon$2.fromWithDefault(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$$anon$2$$anonfun$fromConfigObject$3.apply(ConfigConvert.scala:143)
	at pureconfig.ConfigConvert$$anon$2$$anonfun$fromConfigObject$3.apply(ConfigConvert.scala:133)
	at scala.util.Success.flatMap(Try.scala:231)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:133)
	at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$WrappedDefaultValueConfigConvert$class.fromWithDefault(ConfigConvert.scala:103)
	at pureconfig.ConfigConvert$$anon$2.fromWithDefault(ConfigConvert.scala:128)
	at pureconfig.ConfigConvert$$anon$9.from(ConfigConvert.scala:300)
	at pureconfig.package$.loadConfig(package.scala:71)
	at pureconfig.package$.loadConfig(package.scala:25)
```

If I change the key name from `apiKey` to something longer, like `theApiKey`, it works fine.

**Comment by melrief** [comment]
Ehi @dbousamra, thanks for reporting the issue. I've just tried to reproduce the problem on master but it seems like it's not happening to me. I've used the following code with `sbt core/console`, please let me know if I'm doing something wrong:

```scala
> import pureconfig._
> import com.typesafe.config._
> val config = ConfigFactory.parseString("""{settings:{stormpath:{apiKey:"example"}}}""")
> implicit def hint[T] = ProductHint[T](ConfigFieldMapping(CamelCase, CamelCase))
> case class Config(apiKey: Option[String])
> loadConfig[Config](config, "settings.stormpath")
res0: Either[pureconfig.error.ConfigReaderFailures,Config] = Right(Config(Some(example)))
```

It may be that I'm using a more recent version of pureconfig. What version are you using? Another thing that could help me is to see some code. Do you think you could share the part of the code you use to load the configuration?

**Comment by dbousamra** [comment]
Hey. Thanks. I'll have a more complete example up tomorrow morning (I'm in
Aus, so late ATM). I upgraded to latest version today

**Comment by ruippeixotog** [comment]
Hi @dbousamra! Did you manage to solve your problem?

**Comment by melrief** [comment]
@dbousamra I'm closing this now, if you still have the problem let us know and we will reopen it.
