### ISSUE TITLE
loadConfig throws ConfigException$Missing if the namespace doesn't exists

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#218]
This should return a `Failure`, not throw exception.

```scala
scala> loadConfig[Int](namespace = "foo.bar")
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'foo'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
	at pureconfig.package$$anonfun$loadConfig$2$$anonfun$apply$3.apply(package.scala:45)
	at pureconfig.package$$anonfun$loadConfig$2$$anonfun$apply$3.apply(package.scala:45)
	at scala.util.Either$RightProjection.map(Either.scala:536)
	at pureconfig.package$$anonfun$loadConfig$2.apply(package.scala:45)
	at pureconfig.package$$anonfun$loadConfig$2.apply(package.scala:44)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at pureconfig.package$.loadConfig(package.scala:44)
```

I'm starting to think that we should wrap every part of typesafe config that we use in a safer wrapper.

**Comment by rberenguel** [comment]
What's the most "scalactic" (scalese? scaly?) way of doing this? It seems straightforward enough to let me have a go (at least for this specific instance, covering all typesafe config needs probably more knowledge of pureconfig's internals than what I have

**Comment by ruippeixotog** [comment]
Good catch. I believe the methods we use inside `ConfigConvert` instances are relatively safe (we just need to deal with returned `null` values, which we do). The methods in [package.scala](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/package.scala) were not targeted by our efforts when we changed from `Try` to `Either`, though.

**Comment by melrief** [comment]
@rberenguel have a look at the [wrapper](https://github.com/pureconfig/pureconfig/blob/e4b7ec4d50f2d628230c676a8cde23dc2cc60df2/core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala) that we use to catch all the exception and convert them to a `ConfigReaderFailure`. Specifically, the method [`unsafeToEither`](https://github.com/pureconfig/pureconfig/blob/e4b7ec4d50f2d628230c676a8cde23dc2cc60df2/core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala#L32) does the job of taking a potentially unsafe `f`, run it and wrap the result or exception in a proper type.

@ruippeixotog indeed, let's fix this now.

**Comment by rberenguel** [comment]
Thanks @melrief nice to see this done (going to be useful for the future). I understand you or @ruippeixotog are on this one?

**Comment by leifwickland** [comment]
Rui, please ensure this gets added to the change log.

**Comment by ruippeixotog** [comment]
Thanks @leifwickland, I forgot about it! Added in #250, along with other forgotten entries.
