### ISSUE TITLE
TraversableOnce Generic Decoder broken in 0.8.0

### ISSUE THREAD

**Issue by pjan** [pureconfig/pureconfig#307]
I have a config that contains a `Set[String]` but upon upgrading to 0.8.0, a runtime exception gets thrown

Code:
```scala
case class Config(
    exclude: Set[String]
)
```

Log:
```
service[ERROR] Exception in thread "main" java.lang.NoSuchMethodError: testapp.config.Config.<init>(Z)V
service[ERROR]  at shapeless.LabelledGeneric$$anon$1.from(generic.scala:229)
service[ERROR]  at shapeless.LabelledGeneric$$anon$1.from(generic.scala:226)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$11.$anonfun$from$20(DerivedReaders.scala:268)
service[ERROR]  at scala.util.Either$RightProjection.map(Either.scala:714)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$11.from(DerivedReaders.scala:268)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:123)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault(DerivedReaders.scala:83)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault$(DerivedReaders.scala:82)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:129)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault(DerivedReaders.scala:83)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault$(DerivedReaders.scala:82)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:129)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault(DerivedReaders.scala:83)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault$(DerivedReaders.scala:82)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:129)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault(DerivedReaders.scala:83)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault$(DerivedReaders.scala:82)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:129)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault(DerivedReaders.scala:83)
service[ERROR]  at pureconfig.DerivedReaders1$WrappedDefaultValue.fromWithDefault$(DerivedReaders.scala:82)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
service[ERROR]  at pureconfig.DerivedReaders1$$anon$11.from(DerivedReaders.scala:268)
service[ERROR]  at pureconfig.package$.$anonfun$loadValue$1(package.scala:54)
service[ERROR]  at scala.util.Either$RightProjection.flatMap(Either.scala:702)
service[ERROR]  at pureconfig.package$.loadValue(package.scala:52)
service[ERROR]  at pureconfig.package$.$anonfun$loadConfig$2(package.scala:80)
service[ERROR]  at scala.util.Either$RightProjection.flatMap(Either.scala:702)
service[ERROR]  at pureconfig.package$.$anonfun$loadConfig$1(package.scala:79)
service[ERROR]  at scala.util.Either$RightProjection.flatMap(Either.scala:702)
service[ERROR]  at pureconfig.package$.loadConfig(package.scala:78)
```

**Comment by pjan** [comment]
FWIW: worked fine in `0.7.2`

**Comment by melrief** [comment]
Hey @pjan, thanks for submitting the bug. I've just tried from the shell at it seems to work for me:

```scala
pureconfig> sbt core/test:console
[info] Loading global plugins from /Users/mariop/.sbt/0.13/plugins
[info] Loading project definition from /Users/mariop/prog/pureconfig/project
[info] Set current project to pureconfig (in build file:/Users/mariop/prog/pureconfig/)
[info] Starting scala interpreter...
[info]
Welcome to Scala 2.12.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_66).
Type in expressions for evaluation. Or try :help.

scala> Welcome to the Ammonite Repl 1.0.1
(Scala 2.12.3 Java 1.8.0_66)
@ import pureconfig._
import pureconfig._

@ import com.typesafe.config.ConfigFactory.parseString
import com.typesafe.config.ConfigFactory.parseString

@ case class Config(set: Set[String])
defined class Config

@ loadConfig[Config](parseString("""{ set: ["foo", "bar"] }"""))
res3: Either[error.ConfigReaderFailures, Config] = Right(Config(Set("foo", "bar")))
```

also the tests about `TraversableOnce` are all passing.

I may be wrong and it's difficult to tell only from the stack trace but I think the problem that you are experiencing is caused by some issues in the dependencies of your project. If I have to guess I would say that there is an issue with Shapeless and probably the version using by pureconfig `0.8.0` is different from the one you are using. pureconfig `0.8.0` is using shapeless `2.3.2`.

**Comment by ruippeixotog** [comment]
I'm closing this issue since there's been no activity in the last months. Let me know if there's any update on this!
