### ISSUE TITLE
Reading a custom config file from typesafe

### ISSUE THREAD

**Issue by robbyki** [pureconfig/pureconfig#316]
What is the right way to load a custom configuration file around typesafe? Would like to use a difference resource file other then `application.conf` so trying to figure out how to include `ConfigFactor.load("myfile.conf")`

**Comment by leifwickland** [comment]
@robbyki If you don't mind my asking, what solution did you end up with? What information would you have liked to have seen in the pureconfig documentation to help you find the answer more quickly?

**Comment by robbyki** [comment]
Thank you. I was a little too quick to pose the question but was initially unsure how to just use something like this with pureconfig `  val myconfig = ConfigFactory.load("mycustom.conf")`. Once I did that using typesafe loader then I was able to pass that `myconfig` to pureconfig with the below. Still trying to get a hang of initializing and reading the variables inside my configuration file. 
```
  val simpleConfig: Either[ConfigReaderFailures, Settings] =
    loadConfig[Settings](myconfig, "my.example")
```

**Comment by leifwickland** [comment]
@robbyki 
The slightly easier way accomplish that is:
```
pureconfig.loadConfigFromFiles(Seq("mycustom.conf"))
```

See 
https://github.com/pureconfig/pureconfig/blob/master/docs/whence-the-config-files.md 
and the various load methods in the pureconfig `package.scala`
https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/package.scala#L277
for more details.

**Comment by robbyki** [comment]
Thank you so much! will try that out.

**Comment by bijancn** [comment]
`loadConfigFromFiles` swallows all errors for me:
```
  java.lang.UnsupportedOperationException: empty.reduceLeft                                                                                
  at scala.collection.LinearSeqOptimized.reduceLeft(LinearSeqOptimized.scala:135)                                                                
  at scala.collection.LinearSeqOptimized.reduceLeft$(LinearSeqOptimized.scala:134)                                                             
  at scala.collection.immutable.List.reduceLeft(List.scala:86)                                                                                 
  at scala.collection.TraversableOnce.reduce(TraversableOnce.scala:208)                                                                       
  at scala.collection.TraversableOnce.reduce$(TraversableOnce.scala:208)                                                                         
  at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)                                                                           
  at pureconfig.package$.$anonfun$loadConfigFromFiles$5(package.scala:283)                                                                                                                                           
  at scala.util.Either$RightProjection.map(Either.scala:714)                                                                             
  at pureconfig.package$.loadConfigFromFiles(package.scala:283)                                                                                                                                                      
  at pureconfig.package$.loadConfigFromFilesOrThrow(package.scala:294)
```

**Comment by ruippeixotog** [comment]
@bijancn, please see https://github.com/pureconfig/pureconfig/issues/335. It'll get fixed in the next version.

**Comment by bijancn** [comment]
Cool. Good to know @ruippeixotog ! Been loving the library otherwise!
