### ISSUE TITLE
Pureconfig & spark shading set

### ISSUE THREAD

**Issue by geoHeil** [pureconfig/pureconfig#333]
I cant get pureconfig to work with spark due to clashes with shapeless.
Already using shading:
```
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll
)
```

Already using the suggestion of:
https://github.com/pureconfig/pureconfig/issues/267
and stacktrace:
```
Exception in thread "main" java.lang.NoSuchMethodError: at.geoheil.utils.SampleConfig.<init>(Ljava/lang/String;)V
	at at.geoheil.utils.SparkBaseRunner$anon$macro$8$1.from(SparkBaseRunner.scala:11)
	at at.geoheil.utils.SparkBaseRunner$anon$macro$8$1.from(SparkBaseRunner.scala:11)
	at new_shapeless.LabelledGeneric$$anon$1.from(generic.scala:229)
	at new_shapeless.LabelledGeneric$$anon$1.from(generic.scala:226)
	at pureconfig.DerivedReaders1$$anon$11$$anonfun$from$12.apply(DerivedReaders.scala:268)
	at pureconfig.DerivedReaders1$$anon$11$$anonfun$from$12.apply(DerivedReaders.scala:268)
	at scala.util.Either$RightProjection.map(Either.scala:535)
	at pureconfig.DerivedReaders1$$anon$11.from(DerivedReaders.scala:268)
	at pureconfig.package$$anonfun$pureconfig$package$$loadValue$1.apply(package.scala:53)
	at pureconfig.package$$anonfun$pureconfig$package$$loadValue$1.apply(package.scala:52)
	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
	at pureconfig.package$.pureconfig$package$$loadValue(package.scala:52)
	at pureconfig.package$$anonfun$loadConfig$1$$anonfun$apply$1.apply(package.scala:80)
	at pureconfig.package$$anonfun$loadConfig$1$$anonfun$apply$1.apply(package.scala:79)
	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
	at pureconfig.package$$anonfun$loadConfig$1.apply(package.scala:79)
	at pureconfig.package$$anonfun$loadConfig$1.apply(package.scala:78)
	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
	at pureconfig.package$.loadConfig(package.scala:78)
	at pureconfig.package$.loadConfig(package.scala:66)
	at at.geoheil.utils.ConfigurationUtils$.loadConfiguration(ConfigurationUtils.scala:13)
	at at.geoheil.utils.SparkBaseRunner$class.$init$(SparkBaseRunner.scala:11)
	at at.geoheil.app.SparkJob$.<init>(SparkJob.scala:7)
	at at.geoheil.app.SparkJob$.<clinit>(SparkJob.scala:52)
	at at.geoheil.app.SparkJob.main(SparkJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by leifwickland** [comment]
Which versions of PureConfig and Spark are you using?

**Comment by geoHeil** [comment]
I am using spark 2.20 and the latest pureconfig of: 0.8.0

see https://github.com/geoHeil/spatial-heatmaps/blob/master/esri/build.sbt

**Comment by leifwickland** [comment]
@geoHeil,

Stupid question: Does it work if you _don't_ shade shapeless? It appears that Spark 2.2 includes the version of shapeless that pureconfig depends on. When I build an assembly that does something like this:
```
val pureconfig = ("com.github.pureconfig" %% "pureconfig" % "0.8.0"
  exclude("com.chuusai", "shapeless_2.11")
)
val shapeless = "com.chuusai" %% "shapeless" % "2.3.2" % "provided"

libraryDependencies ++= Seq(pureconfig, shapeless)
```

...and has no related shading, then there's no shapeless in my fat jar, but I am able to load the config when running the app through `spark-submit`.

If that works for you, it looks like we need to update the pureconfig documentation to add a caveat about not needing to shade starting with Spark 2.2

If that doesn't work for you, can you construct a smaller reproduction of the problem, please? While it was extremely useful to see your project, I can't build it because it depends on an unavailable SNAPSHOT.

**Comment by geoHeil** [comment]
Thanks for looking at it. here is a minimal sample https://github.com/geoHeil/minimalPure

simply run `set run`

**Comment by geoHeil** [comment]
disabling assembly does not change the problem.

**Comment by leifwickland** [comment]
@geoHeil Did you mean "disabling shading" or "disabling assembly?"

**Comment by leifwickland** [comment]
@geoHeil Did you mean `sbt run` instead of `set run`?

**Comment by leifwickland** [comment]
Thanks for providing a minimal sample repo.

I wouldn't expect `sbt run` to do anything good because your spark dependencies are (correctly) marked as `provided`, so they are not included in the classpath for `sbt run`.

The error I get when I try `sbt run` is:
```
[error] Exception in thread "main" java.lang.IllegalArgumentException: Unable to instantiate SparkSession with Hive support because Hive classes are not found.
```

Moreover, `sbt run` doesn't exercise the assembly process, so all of the shading aspects of this discussion are moot.

I removed the line from your `build.sbt` that shaded shapeless. I added the following `object` to your code:

```
object SampleConfig {
  def main(a: Array[String]): Unit = {
    val conf = pureconfig.loadConfig[SampleConfig]
    println("conf: " + conf)
  }
}
```

I created an assembly. I copied that to my cluster. I ran it like:
```
> spark-submit  --deploy-mode client  --class at.geoheil.utils.SampleConfig ~lwickland/sparkMiniSample-assembly-0.1-SNAPSHOT.jar
```
It printed:
```
conf: Right(SampleConfig(../data/trip_data/trip_data_1.csv,../data/aggregatedResult.csv))
```

All that to say, aside from the usual problems of trying to run spark inside of sbt, I think minus the shade rule, your assembly should run fine on a proper spark cluster.

Please let me know if that's not true.

**Comment by geoHeil** [comment]
You are right - there must have been a different problem last night. When modifying the minimal sample it works.
