### ISSUE TITLE
`loadConfigFromFiles` throws an exception if no files are read

### ISSUE THREAD

**Issue by mtomko** [pureconfig/pureconfig#335]
The method `loadConfigFromFiles` takes a `Traversable[Path]` as an argument. It checks whether the `Traversable` is empty and handles the error by returning a `Left`.

Subsequently, if it turns out that the `Traversable[Path]` contains only missing or otherwise unreadable files, it passes this initial check but results in an exception from the call to `reduce` on an empty collection:

Here is a sample stack trace (from version `0.8.0` of pureconfig and Scala 2.12):
```scala
java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.LinearSeqOptimized.reduceLeft(LinearSeqOptimized.scala:135)
	at scala.collection.LinearSeqOptimized.reduceLeft$(LinearSeqOptimized.scala:134)
	at scala.collection.immutable.List.reduceLeft(List.scala:86)
	at scala.collection.TraversableOnce.reduce(TraversableOnce.scala:208)
	at scala.collection.TraversableOnce.reduce$(TraversableOnce.scala:208)
	at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
	at pureconfig.package$.$anonfun$loadConfigFromFiles$5(package.scala:296)
	at scala.util.Either$RightProjection.map(Either.scala:714)
	at pureconfig.package$.loadConfigFromFiles(package.scala:296)
	at org.broadinstitute.gpp.aguila.Config$.load(Config.scala:43)
	at org.broadinstitute.gpp.aguila.Aguila$.main(Aguila.scala:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.twitter.app.App.$anonfun$nonExitingMain$3(App.scala:225)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.app.App.nonExitingMain(App.scala:224)
	at com.twitter.app.App.nonExitingMain$(App.scala:202)
	at org.broadinstitute.gpp.aguila.Aguila$.nonExitingMain(Aguila.scala:30)
	at com.twitter.app.App.main(App.scala:190)
	at com.twitter.app.App.main$(App.scala:188)
	at org.broadinstitute.gpp.aguila.Aguila$.main(Aguila.scala:30)
	at org.broadinstitute.gpp.aguila.Aguila.main(Aguila.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```
The scaladocs include the following note:

> Note: If an element of `files` references a file which doesn't exist or can't be read, it will silently be ignored.

@jcazevedo noted in the gitter channel that the behaviour changed on #245 and reverted on #262. 

It was agreed by @jcazevedo and @melrief  that this method should not throw, but @jcazevedo pointed out that returning an error when files could not be read conflicts with the documented behavior of silently ignoring files that don't exist or can't be read.

**Comment by kiara-riley** [comment]
This seems to be caused by line:
https://github.com/pureconfig/pureconfig/blob/0824a9739364864d79b034b9125db88a1ebdae5c/core/src/main/scala/pureconfig/package.scala#L293

In the case that you only have a single unreadable file as input, the result from the foldLeft ends up being an empty `Seq`. There needs to be a check to make sure the `Seq[TypesafeConfig]` is non-empty if the behavior is really supposed to be that files that can't be read are silently ignored.

**Comment by ruippeixotog** [comment]
This shouldn't be difficult to tackle, we just need to settle on the semantics for this :)

I see use cases for both of the behaviors. For many years I relied on the loading of a chain of optional configuration files with a well-defined order (just like Typesafe config does out of the box with `reference.conf` and `application.conf`, but with even more layers). The current `loadConfigFromFiles` is ideal for those situations, where you are really expecting that most (even all) files are missing. On the other hand, I obviously recognize the usefulness of having a method that loads multiple non-optional files and handles gracefully (through `ConfigReaderFailures`) missing files.

What do you think of adding a second argument `failOnReadError` (with a default of `false`) that makes the method return a `Left` if _any_ of the files don't exist or can't be read? Additionally, I propose that the default `loadConfigFromFiles` (with `failOnReadError = false`) starts accepting empty lists of files, using an empty config in that case, just like Typesafe config does.

@jcazevedo, what do you think? @mtomko, @kraigmckernan, is this still a useful thing for you?

**Comment by kiara-riley** [comment]
> What do you think of adding a second argument failOnReadError (with a default of false) that makes the method return a Left if any of the files don't exist or can't be read? Additionally, I propose that the default loadConfigFromFiles (with failOnReadError = false) starts accepting empty lists of files, using an empty config in that case, just like Typesafe config does.

That sounds like it would fix the issue I have with the method. I would almost always prefer having the application stop(due to `Left`) when a config file can't be read as the application is misconfigured at that point to me.

That, along with fixing this bug sounds ideal to me.

**Comment by mtomko** [comment]
I think it sounds great. I can certainly envision circumstances where we'd want to stop if a file was not found, but the system where I encountered this issue originally is more in the mold of having a chain of files, some of which may be absent, which together add up to a valid and complete configuration.
