### ISSUE TITLE
shapeless method not found even though shaded in case of yarn cluster mode of spark

### ISSUE THREAD

**Issue by geoHeil** [pureconfig/pureconfig#337]
for a configuration class of:

```
case class Table(
  db: String,
  sqlToGenerateTheTable: String,
  outputPath: String,
  aa: Seq[String],
  bb: Seq[String])
```

I get the error of:
`Table.<init>(Ljava/lang/String;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;)V)`
when running it in yarn cluster mode!
yarn client mode works just fine ... what could be the problem here? 

Shading of shapeless was already applied:

```
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll
)
```

spark is HDP 2.6.1 / spark-version of 2.1.1

**Comment by geoHeil** [comment]
just found: https://q-a-assistant.com/computer-internet-technology/2564128_spark-not-working-with-pureconfig.html

**Comment by geoHeil** [comment]
However, this does not yet do the trick for me. 

```
java.lang.NoSuchMethodError: pureconfig.ConfigReader$.labelledHConsConfigReader(Lshadeshapless/Witness;Lpureconfig/Derivation;Lshadeshapless/Lazy;Lpureconfig/ProductHint;)Lpureconfig/DerivedReaders1$WrappedDefaultValue;
```

**Comment by geoHeil** [comment]
I will need to try the `inAll` modifier on Monday: 
`assemblyShadeRules in assembly := Seq(ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll)`

**Comment by geoHeil** [comment]
just found: https://q-a-assistant.com/computer-internet-technology/2564128_spark-not-working-with-pureconfig.html

```
lazy val pureconfigVersion = "0.8.0"

libraryDependencies ++= Seq(
  "com.github.pureconfig" %% "pureconfig" % pureconfigVersion,
 .......
)

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("shapeless.**" -> "shadeshapless.@1")
    .inLibrary("com.chuusai" % "shapeless_2.11" % "2.3.2")
    .inLibrary("com.github.pureconfig" %% "pureconfig" % pureconfigVersion)
    .inProject
)
```

However, this does not yet do the trick for me. This is the new error: 

```
java.lang.NoSuchMethodError: pureconfig.ConfigReader$.labelledHConsConfigReader(Lshadeshapless/Witness;Lpureconfig/Derivation;Lshadeshapless/Lazy;Lpureconfig/ProductHint;)Lpureconfig/DerivedReaders1$WrappedDefaultValue;
```
Apparently, others can reproduce the same problem here: https://stackoverflow.com/questions/43611147/spark-not-working-with-pureconfig

**Comment by leifwickland** [comment]
@geoHeil,

There should be some other context around the error that you posted. `
Table.<init>(Ljava/lang/String;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;)V)` is the JVM signature of a method. Most likely the error is saying that the method isn't found, but it'd be good to ensure that's the case before we try to investigate further.

In general loading configuration with yarn cluster mode is a pain because the driver is executing on an arbitrary box in the cluster. When the driver tries to read the configuration from disk, it's not going to search the disk of the box from which you launched `spark-submit`. In my experience, unless you deploy and sync your configuration to every node in the yarn cluster or you're pulling your configuration from some central authority or a shared file system, yarn cluster mode and config files do not play well together.

Also, please do your best to avoid `q-a-assistant.com`. It's a terrible rip off-site that simply copies and reposts stackoverflow questions. There have been many such sites over the years. Please don't feed the trolls.

**Comment by geoHeil** [comment]
Sorry for that. Will only link to SF in the future. 

Indeed it reads method not found in the stack trace. However the configuration is passed read correctly. This is not the problem -at least I believe so/ get a different error if some fields are not present. 

See the stack trace below for some more context:

```
ew_shapeless.LabelledGeneric$$anon$1.from(generic.scala:226)
        at pureconfig.DerivedReaders1$$anon$11$$anonfun$from$12.apply(DerivedReaders.scala:268)
        at pureconfig.DerivedReaders1$$anon$11$$anonfun$from$12.apply(DerivedReaders.scala:268)
        at scala.util.Either$RightProjection.map(Either.scala:535)
        at pureconfig.DerivedReaders1$$anon$11.from(DerivedReaders.scala:268)
        at pureconfig.DerivedReaders1$$anon$4$$anonfun$from$6.apply(DerivedReaders.scala:186)
        at pureconfig.DerivedReaders1$$anon$4$$anonfun$from$6.apply(DerivedReaders.scala:184)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at pureconfig.DerivedReaders1$$anon$4.from(DerivedReaders.scala:184)
        at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:123)
        at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
        at pureconfig.DerivedReaders1$WrappedDefaultValue$class.fromWithDefault(DerivedReaders.scala:83)
        at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
        at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:129)
        at pureconfig.DerivedReaders1$$anon$8.fromConfigObject(DerivedReaders.scala:110)
        at pureconfig.DerivedReaders1$WrappedDefaultValue$class.fromWithDefault(DerivedReaders.scala:83)
        at pureconfig.DerivedReaders1$$anon$8.fromWithDefault(DerivedReaders.scala:110)
        at pureconfig.DerivedReaders1$$anon$11.from(DerivedReaders.scala:268)
        at pureconfig.package$$anonfun$pureconfig$package$$loadValue$1.apply(package.scala:53)
        at pureconfig.package$$anonfun$pureconfig$package$$loadValue$1.apply(package.scala:52)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at pureconfig.package$.pureconfig$package$$loadValue(package.scala:52)
        at pureconfig.package$$anonfun$loadConfig$1$$anonfun$apply$1.apply(package.scala:80)
        at pureconfig.package$$anonfun$loadConfig$1$$anonfun$apply$1.apply(package.scala:79)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at pureconfig.package$$anonfun$loadConfig$1.apply(package.scala:79)
        at pureconfig.package$$anonfun$loadConfig$1.apply(package.scala:78)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at pureconfig.package$.loadConfig(package.scala:78)
        at pureconfig.package$.loadConfig(package.scala:66)
        at my.conf.ConfigurationUtils$.loadConfiguration(ConfigurationUtils.scala:42)
        at my.conf.SparkBaseRunner$class.$init$(SparkBaseRunner.scala:10)
        at my.app.HashDataFrame$.<init>(HashDataFrame.scala:7)
        at my.app.HashDataFrame$.<clinit>(HashDataFrame.scala)
        at my.app.HashDataFrame.main(HashDataFrame.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
17/12/07 10:28:37 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.NoSuchMethodError: my.conf.Table.<init>(Ljava/lang/String;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;)V)
17/12/07 10:28:37 INFO ApplicationMaster: Deleting staging directory hdfs://hadoop/user/username/.sparkStaging/application_1512556943206_2148
17/12/07 10:28:37 INFO ShutdownHookManager: Shutdown hook called
```

**Comment by geoHeil** [comment]
Actually, after some more fiddling it turns out that:

```
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("shapeless.**" -> "shadeshapless.@1")
    .inLibrary("com.chuusai" % "shapeless_2.11" % "2.3.2")
    .inLibrary("com.github.pureconfig" % "pureconfig_2.11" % pureconfigVersion)
    .inLibrary("com.github.pureconfig" % "pureconfig-macros_2.11" % pureconfigVersion)
    .inProject
)
```
at least fixes the missing class - and in my opinion should be the same as `inAll`

On Monday I will be able to further experiment with yarn cluster and will also try to use `spark.driver.userClasspathFirst=true`
