### ISSUE TITLE
Pureconfig inconsistently fails with "Duplicate id: 45"

### ISSUE THREAD

**Issue by jgogstad** [pureconfig/pureconfig#414]
Hey,

I have an unstable test that fails every 30th run or so with the following stacktrace:

    Cannot convert configuration to a model.DeploymentTemplate.
      Failures are:   at 'deployment-template.spec.dag':
        - (file:/var/jenkins_home/[snip]/hourly.conf:6) No valid coproduct choice found for '{"backfill":"2018-08-12","location":"eu"}'
        - (file:/var/jenkins_home/[snip]/hourly.conf:6) assertion failed: Duplicate id: 45.
        at pureconfig.package$.getResultOrThrow(package.scala:138)  at pureconfig.package$.loadConfigOrThrow(package.scala:206)
        at [snip]

The only coproduct in the object graph is the `location` field; it's parsed into the `Location` class defined as this (the assertion error most likely comes from [Enumeration.Val#242](https://github.com/scala/scala/blob/2.12.x/src/library/scala/Enumeration.scala#L242) which I subclass.)

    object Location extends Enumeration {
      val Asia = Location("asia", "asia", Region.UsCentral1)
      val Eu   = Location("eu", "europe", Region.EuropeWest1)
      val Us   = Location("us", "us", Region.UsCentral1)
    
      class Location(val name: String, val longName: String, val defaultRegion: Region) extends Val(name = name)

      def apply(name: String, longName: String, region: Region) = new Location(name, longName, region)

      def unapply(string: String): Option[Location] =
        all.find(l => l.toString.equalsIgnoreCase(string) || l.longName.equalsIgnoreCase(string)) // This is a bit harder to do with values(), we're not expecting any more values to this enum, so taking the easy route
    
      def all: Seq[Location] = Seq(Asia, Eu, Us)
    }

Using this reader:

    implicit val locationReader: ConfigReader[Location] = ConfigReader.fromNonEmptyStringOpt(Location.unapply)

The target case class looks like

    case class Hourly(backfill: LocalDate, location: Location)

**Observable odd behavior**

* The assertion error most likely comes from [Enumeration.scala#242](https://github.com/scala/scala/blob/2.12.x/src/library/scala/Enumeration.scala#L242). I'm guessing that mutable state in `vmap` is the source of this, although I don't see how.
* How on earth the counter as reached 45 is beyond me, it's an enum with 3 instances. We're on Jenkins and multiple tests run in parallel, but I don't see any static shared state that could cause this.

As I said, the parsing works 9 out of 10 times.

**Comment by ruippeixotog** [comment]
Hi @jgogstad, that's very strange indeed... do you mind creating a minimal test project using the latest Scala version where this can be reproduced?

This is most probably an `Enumeration` bug since I can't think of anything PureConfig does that may cause this, but I can take a look to confirm that.

**Comment by jgogstad** [comment]
I'll see what I can cook together. I had a closer look at `Enumeration` in the standard library, and I don't see how there's not a race condition there. Given the example `Enumeration` above

* `object Location extends Enumeration` defines a static context with mutable state, accessible to all threads on the JVM.
* The `Val` constructor reads mutable state from that context at [Enumeration.Val#239](https://github.com/scala/scala/blob/2.12.x/src/library/scala/Enumeration.scala#L239), `nextId`, and then writes back to the same mutable state at [Enumeration.Val#245](https://github.com/scala/scala/blob/2.12.x/src/library/scala/Enumeration.scala#L245)
* If multiple threads enters the `Val` constructor for different instances of the enumeration, that leads to a race condition.

Is there something I'm not seeing?

**Comment by nigredo-tori** [comment]
@jgogstad, I'm not sure that PureConfig supports `Enumeration` out of the box. AFAIK, we're using Shapeless for everything, and the whole point of Shapeless is doing everything at compile time. Scala's `Enumeration`, on the other hand, relies on run time trickery to distinguish its elements. These two approaches don't mix at all, which might be the reason for the first error (`No valid coproduct choice found`).

The problem here is not the error itself, but rather the fact that the code actually compiles. Are you using a custom `ConfigReader` instance?

The failed assertion seems much weirder. There are a lot of things that can go wrong with `Enumeration`. 
1. Are you sure you don't instantiate `Location` anywhere else? Your `apply` method and the `Location` constructor are both public...
2. Is there serialization happening anywhere?
3. What test framework and Scala version are you using?

A test case reproducing the error would certainly help this search.

**Comment by nigredo-tori** [comment]
Actually, looking back on the first error message, we see that PureConfig can't find a coproduct branch for this value:

`{"backfill":"2018-08-12","location":"eu"}`

It seems to me that the `Location` you provided doesn't correspond to this whole object, but rather to one of its fields. You might want to look for the problem a level above the `Location`.

**Comment by jgogstad** [comment]
@nigredo-tori

> The problem here is not the error itself, but rather the fact that the code actually compiles. Are you using a custom ConfigReader instance?

Yes, I'm using a `ConfigReader`, it's in the middle of the top post `implicit val locationReader ...`; it works 9 out of 10 times.

> Are you sure you don't instantiate Location anywhere else? Your apply method and the Location constructor are both public...

Good point, it should be private. It's not invoked from anywhere else, but I'm pretty sure that ScalaTest can hit that `apply` method in parallel when it runs tests in parallel.

> Is there serialization happening anywhere?

No

> What test framework and Scala version are you using?

ScalaTest

I'll work on cooking together a smaller test case. Thanks for taking the time to look at it.

**Comment by nigredo-tori** [comment]
> Yes, I'm using a ConfigReader, it's in the middle of the top post implicit val locationReader ...; it works 9 out of 10 times.

My apologies, I missed that... 

> I'm pretty sure that ScalaTest can hit that `apply` method in parallel when it runs tests in parallel.

This shouldn't matter unless you use this method somewhere else. `val` initialization is a part of the `object` creation, and should happen exactly once and in the same thread. Unless your `val`s are `lazy` - but even then they are `synchronized` on the parent object.

**Comment by ruippeixotog** [comment]
Closing this due to inactivity. Feel free to open it again if the issue persists and you're able to provide a minimal reproducible example.
