### ISSUE TITLE
Pureconfig can't parse JSON

### ISSUE THREAD

**Issue by whoisvolos** [pureconfig/pureconfig#520]
Good day!
I am using version 0.11.1 and Scala 2.12, trying to parse JSON to case class.

```
case class Ex(foo: String)

val strCfg = """{"foo":"bar"}"""
val config = pureconfig.loadConfigOrThrow[Ex](strCfg)
```

Getting

```
Cannot convert configuration to a me.playground.PureSpec$Ex. Failures are:
  - path parameter: Invalid path '{"foo":"bar"}': Token not allowed in path expression: '{' (you can double-quote this token if you really want it here).

pureconfig.error.ConfigReaderException: Cannot convert configuration to a me.playground.PureSpec$Ex. Failures are:
  - path parameter: Invalid path '{"foo":"bar"}': Token not allowed in path expression: '{' (you can double-quote this token if you really want it here).

	at pureconfig.package$.getResultOrThrow(package.scala:139)
	at pureconfig.package$.loadConfigOrThrow(package.scala:161)
	at me.playground.PureSpec.$anonfun$new$2(PureSpec.scala:17)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.invokeWithFixture$1(FunSpecLike.scala:452)
	at org.scalatest.FunSpecLike.$anonfun$runTest$1(FunSpecLike.scala:464)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSpecLike.runTest(FunSpecLike.scala:464)
	at org.scalatest.FunSpecLike.runTest$(FunSpecLike.scala:446)
	at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$runTests$1(FunSpecLike.scala:497)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSpecLike.runTests(FunSpecLike.scala:497)
	at org.scalatest.FunSpecLike.runTests$(FunSpecLike.scala:496)
	at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$run$1(FunSpecLike.scala:501)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSpecLike.run(FunSpecLike.scala:501)
	at org.scalatest.FunSpecLike.run$(FunSpecLike.scala:500)
	at org.scalatest.FunSpec.run(FunSpec.scala:1630)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

Error is a bit meaningless for me, readme tells about possibility to parse JSON, but full doc does not say smth special about JSON case. No problem with Typesafe configs though.

**Comment by ruippeixotog** [comment]
Hi @whoisvolos! `loadConfigOrThrow` has many overloaded versions, and you're actually calling [this one](https://static.javadoc.io/com.github.pureconfig/pureconfig-core_2.12/0.11.1/pureconfig/index.html#loadConfigOrThrow[Config](namespace:String)(implicitevidence$2:scala.reflect.ClassTag[Config],implicitreader:pureconfig.Derivation[pureconfig.ConfigReader[Config]]):Config), which takes a namespace and not a config in string format - you probably want to call `loadConfig[Ex](ConfigFactory.parseString(strCfg))` instead. I agree that the error message is very hard to understand.

**Comment by whoisvolos** [comment]
Yes, now it works great! Thank you!
