### ISSUE TITLE
Bug loading resources config with ConfigSource.resources("/application-dev.conf")

### ISSUE THREAD

**Issue by karlroberts** [pureconfig/pureconfig#625]
Hi,

with version 0.12.1

`ConfigSource.resources(resourceName)`   fails yet `ConfigSource.url(..)` works... specifically see this 
[code gist ](https://gist.github.com/karlroberts/2ae14ce2b7b48b745d0cd3c5a3a5c620) 

I can find the resource turn it into a URL and resolve it OK using `ConfigSource.url(theurl)` but if I use resources for an absolute resource it fails with the exception

```
[main] ERROR [2019-10-22 16:37:20,957] [c.s.t.MainServer$] Uncaught exception in main class. Exiting
java.lang.ExceptionInInitializerError: null
	at com.mycompany.foo.MainServer$.run(MainServer.scala:37)
	at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
	at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:36)
	at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
	at cats.effect.IOApp.main(IOApp.scala:67)
	at cats.effect.IOApp.main$(IOApp.scala:66)
	at com.mycompany.foo.MainServer$.main(MainServer.scala:33)
	at com.mycompany.foo.MainServer.main(MainServer.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: pureconfig.error.ConfigReaderException: Cannot convert configuration to a com.skyfii.tokeniser.config.Configuration. Failures are:
  - Unable to read resource /application-dev.conf (resource not found on classpath: /application-dev.conf).

	at pureconfig.ConfigSource.loadOrThrow(ConfigSource.scala:80)
	at pureconfig.ConfigSource.loadOrThrow$(ConfigSource.scala:77)
	at pureconfig.ConfigSource$$anon$2.loadOrThrow(ConfigSource.scala:315)
	at mycompany.foo.config.Configuration$.forEnvironment(Configuration.scala:51)
	at mycompany.foo.ServerStream$.<init>(MainServer.scala:58)
	at mycompany.foo.ServerStream$.<clinit>(MainServer.scala)
	... 13 common frames omitted
```

**Comment by ruippeixotog** [comment]
To load resources from `src/main/resources` you need to remove the leading slash. `application-dev.conf` should work well in your case.

`ConfigSource#resources` delegates to Typesafe Config `ConfigFactory#parseResources`, which in turn uses `Thread.currentThread().getContextClassLoader().getResources`. Everything that works with this last method should work with `ConfigSource`, too.

**Comment by karlroberts** [comment]
Well, there's "should work" and "works" :-) and unfortunately this does not work.

I can confirm that removing the "/" does not work and has the same error except the message now says

`Unable to read resource application-dev.conf (resource not found on classpath: application-dev.conf) `
besides I don't think you are right, the [java spec for Resources](https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html#res_names) clearly states that adding a "/" to the front makes it an absolute path in the classpath, in this case `src/main/resources` is at the root of the classpath, and besides look at the [gist](https://gist.github.com/karlroberts/2ae14ce2b7b48b745d0cd3c5a3a5c620)   the line with : 

`getClass.getResource(envSpecificConfigPath)`  with `envSpecifigConfigPath == "/application-dev.conf"`

succeeds as then proven by the fact that I can then do : 

    val url = getClass.getResource(envSpecificConfigPath).toURI.toURL
    val conf = ConfigSource.url(url).withFallback(ConfigSource.default)
    ...
    conf.at("conf").loadOrThrow[Configuration]

and the config values in `src/main/resources/application-dev.conf` are parsed and merged into the Configuration.

**Comment by ruippeixotog** [comment]
Right :)

Are you testing this by running `sbt run`? If so, are you explicitly forking the JVM in SBT settings? You may be suffering from a known pitfall of using Typesafe Config (and PureConfig) in an SBT environment, where they do some wild tweaks to class loaders to speed up loading (see https://gitter.im/melrief/pureconfig?at=5d8ddd7573dd29627ebe5ab2 for a discussion on this).

If that's the case, you can add `Compile / run / fork := true` to your build and it will likely work. #614 will help you in the future by allowing you to specify your own class loader at loading time (where you can specify `getClass.getClassLoader`).

**Comment by ruippeixotog** [comment]
Closing due to inactivity. Feel free to reopen if you are still experiencing the issue and I'll take another look!
